"""update appointment statuses

Revision ID: 93147b559385
Revises: 28cd672bb90f
Create Date: 2026-07-26 07:24:05.781079

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '93147b559385'
down_revision: Union[str, Sequence[str], None] = '28cd672bb90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
